Add all headers from OdysseyReversed
open-ead/agl pull request #2
Opened 2021-12-17 14:32 UTC by MonsterDruide1

This PR adds all existing header files from the OdysseyReversed project by shibbo (https://github.com/shibbo/OdysseyReversed/tree/master/include/agl).

2021-12-17 14:33 UTC, MonsterDruide1 commented
Before merging, the necessary changes in `sead` have to be done, and `src/stub.cpp` has to be removed. This file was only added to include all headers, to point out compiler issues.

2021-12-17 20:37 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/agl/2)* status: 0 of 28 files reviewed, 1 unresolved discussion

___
*[src/stub.cpp, line 1 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr95bs809OH2zcQFx4o:-Mr95bs938NDBru5wbJw:bp92vlt) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/src/stub.cpp#L1)):*
> ```cpp
> #include <agl/util.h>
> ```

Remove this file before merging.


<!-- Sent from Reviewable.io -->

2021-12-17 20:48 UTC, leoetlino submitted a review, later dismissed
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/agl/2)* status: all files reviewed, 25 unresolved discussions (waiting on @leoetlino and @MonsterDruide1)

___
*[include/agl/aglDisplayList.h, line 17 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr95IUc-UII1o1F_8IL:-Mr95IUdCjjE9-pwbN-M:bbbrsid) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglDisplayList.h#L17)):*
> ```objc
>     virtual ~DisplayList();
> 
>     void setControlMemeory(void*, s32);
> ```

Is this a typo?

Please add parameter names here and wherever possible
___
*[include/agl/aglDisplayList.h, line 19 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr95OKK4pivzc-Q8Vz1:-Mr95OKK4pivzc-Q8Vz2:b5drbu0) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglDisplayList.h#L19)):*
> ```objc
>     void setControlMemeory(void*, s32);
>     void clear();
>     void setBuffer(agl::GPUMemAddr<u8>, u64);
> ```

no need for agl:: (please fix this in the other files as well)
___
*[include/agl/aglDisplayList.h, line 33 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr95kul7ctE-G7upLTH:-Mr95kul7ctE-G7upLTI:bvb7293) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglDisplayList.h#L33)):*
> ```objc
>     u64 calcRemainingSize();
> 
>     u64 _8;
> ```

These should be private (please fix this in the other headers as well)
___
*[include/agl/aglDisplayList.h, line 36 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr96gx1BTEiqBDrwMGr:-Mr96gx1BTEiqBDrwMGs:b44ozce) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglDisplayList.h#L36)):*
> ```objc
>     u64 _10;
>     u64 _18;
>     u32 mUsedSize;  // _20
> ```

We don't do this kind of offset comment unless really warranted
___
*[include/agl/aglDisplayList.h, line 39 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr95TXB-ykbQEIlq6hz:-Mr95TXB-ykbQEIlq6i-:bcipxg0) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglDisplayList.h#L39)):*
> ```objc
>     u32 _24;
>     u32 mSize;  // _28
>     u32 _2C;
> ```

lowercase (please fix everywhere)
___
*[include/agl/aglDisplayList.h, line 46 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr95UdiDCaRjctRxy40:-Mr95UdiDCaRjctRxy41:b-3uqirp) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglDisplayList.h#L46)):*
> ```objc
>     u32 _24C;
>     u64 _250;
>     char* mDisplayName;  // _258
> ```

This should most likely be `const char*`
___
*[include/agl/aglDrawContext.h, line 24 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr96tE-3xJSgr1WrAUa:-Mr96tE-3xJSgr1WrAUb:b-af8agz) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglDrawContext.h#L24)):*
> ```objc
> 
>     agl::DisplayList* mDisplayList;  // _F0
>     u64* _F8;                        // agl::RenderBuffer*
> ```

this shouldn't be a comment -- the type should just be fixed
___
*[include/agl/aglDrawContext.h, line 33 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr97euZDTJmtezso5Vr:-Mr97euZDTJmtezso5Vs:b-p7zlr0) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglDrawContext.h#L33)):*
> ```objc
>     sead::CriticalSection mCriticalSection;  // _110
> };
> };  // namespace agl
> ```

Missed this earlier, but there's no need to use a semicolon after a closing brace for namespaces.
___
*[include/agl/aglRenderBuffer.h, line 22 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr96z0_5y52A_YWcOZW:-Mr96z0_5y52A_YWcOZX:bqj6sep) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglRenderBuffer.h#L22)):*
> ```objc
> public:
>     RenderBuffer();
>     RenderBuffer(const sead::Vector2<f32>&, const sead::BoundBox2<f32>&);
> ```

Vector2f, BoundBox2f
___
*[include/agl/aglRenderBuffer.h, line 41 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr9747TD0iRe2vCdnmA:-Mr9747TD0iRe2vCdnmB:b-jtrbmn) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglRenderBuffer.h#L41)):*
> ```objc
>     u32 _18;
>     u32 _1C;
>     agl::RenderTargetColor* _20;
> ```

are you sure this isn't an array?
___
*[include/agl/aglRenderTargetColor.h, line 6 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr979ghCPUtPmKMq9QI:-Mr979ghCPUtPmKMq9QJ:b-97yaiy) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglRenderTargetColor.h#L6)):*
> ```objc
> 
> namespace agl {
> class RenderTargetColor : agl::TextureData {
> ```

missing `public`
___
*[include/agl/aglTextureData.h, line 12 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr97F5H-332qVcyqSdt:-Mr97F5H-332qVcyqSdu:b4af60p) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglTextureData.h#L12)):*
> ```objc
>     class CompressToWork {
>     public:
>         CompressToWork(const agl::TextureData&);
> ```

explicit
___
*[include/agl/aglTextureData.h, line 52 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr97HqV7K6CsicTLE08:-Mr97HqV7K6CsicTLE09:b-y6fsv0) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglTextureData.h#L52)):*
> ```objc
>     agl::TextureFormat mTextureFormat;  // _54
>     u8 _58[0x120 - 0x58];
>     char* _120;  // "agl::TextureData string"
> ```

`const char*`
___
*[include/agl/util.h, line 4 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr97PUCCS3D8rcZBton:-Mr97PUCCS3D8rcZBtoo:b-jr2pgf) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/util.h#L4)):*
> ```objc
> 
> namespace agl {
> enum TextureType {
> ```

enum class?
___
*[include/agl/detail/aglFileIOMgr.h, line 9 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr97SyS-pBzsPEEDQ10:-Mr97SyS-pBzsPEEDQ11:b-i6dwwm) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/detail/aglFileIOMgr.h#L9)):*
> ```objc
> 
> namespace sead {
>     namespace hostio {
> ```

formatting
___
*[include/agl/detail/aglFileIOMgr.h, line 38 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr97VCEEv1aaXqoQRQl:-Mr97VCEEv1aaXqoQRQm:b-e0y07i) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/detail/aglFileIOMgr.h#L38)):*
> ```objc
>         u64 _18;
>         u64 _20;
>         char* mMsg;  // _28
> ```

const char*
___
*[include/agl/driver/aglNVNtexture.h, line 18 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr98-PQAzSSsZEw7VLb:-Mr98-PQAzSSsZEw7VLc:bz7fkuf) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/driver/aglNVNtexture.h#L18)):*
> ```objc
>     void releaseTexture();
>     void updateTexId_(s32 newID);
>     // agl::driver:NVNtexture_ operator=(const agl::driver::NVNtexture_&);
> ```

Code that's been commented out should be removed.
___
*[include/agl/shader/aglShaderCompileInfo.h, line 24 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr98BFR9IIuMX5F-Ryt:-Mr98BFR9IIuMX5F-Ryu:b-e0y07i) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/shader/aglShaderCompileInfo.h#L24)):*
> ```objc
>     void create(s32, s32 bufferSize, sead::Heap*);
>     void clearVariation();
>     void pushBackVariation(char const*, char const*);
> ```

const char*
___
*[include/agl/shader/aglShaderCompileInfo.h, line 27 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr985Xt3Pt1uJh758mK:-Mr985Xt3Pt1uJh758mL:by31yug) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/shader/aglShaderCompileInfo [...]

2021-12-17 21:17 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/agl/2)* status: 3 of 28 files reviewed, 25 unresolved discussions (waiting on @leoetlino and @MonsterDruide1)

___
*[include/agl/aglDisplayList.h, line 17 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr95IUc-UII1o1F_8IL:-Mr9Bg-J6QmuWQIHFCnf:b-b35f96) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglDisplayList.h#L17)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Is this a typo?

Please add parameter names here and wherever possible
</blockquote></details>

Yes, that was a typo. Fixed.

However, I won't add parameter names for now. If this is absolutely required for merging this PR, I can come back to it later.
___
*[include/agl/aglDisplayList.h, line 36 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr96gx1BTEiqBDrwMGr:-Mr9EmBi7ZWpml8Wpwxw:b-896fix) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglDisplayList.h#L36)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

We don't do this kind of offset comment unless really warranted
</blockquote></details>

Done.
___
*[include/agl/aglDisplayList.h, line 39 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr95TXB-ykbQEIlq6hz:-Mr9EmOvEboFlr4mfW6q:b-896fix) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglDisplayList.h#L39)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

lowercase (please fix everywhere)
</blockquote></details>

Done.
___
*[include/agl/aglDrawContext.h, line 24 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr96tE-3xJSgr1WrAUa:-Mr9Eo3e8B_lmnX46cZK:b-896fix) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglDrawContext.h#L24)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

this shouldn't be a comment -- the type should just be fixed
</blockquote></details>

Done.
___
*[include/agl/aglDrawContext.h, line 33 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr97euZDTJmtezso5Vr:-Mr9EopwA2DJgHcxmzGy:b-896fix) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglDrawContext.h#L33)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Missed this earlier, but there's no need to use a semicolon after a closing brace for namespaces.
</blockquote></details>

Done.
___
*[include/agl/detail/aglFileIOMgr.h, line 9 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr97SyS-pBzsPEEDQ10:-Mr9F1JeEMtSIhnT9Ybi:b-896fix) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/detail/aglFileIOMgr.h#L9)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

formatting
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-17 21:28 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/agl/2)* status: 3 of 28 files reviewed, 25 unresolved discussions (waiting on @leoetlino and @MonsterDruide1)

___
*[include/agl/aglDisplayList.h, line 19 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr95OKK4pivzc-Q8Vz1:-Mr9HyJ42hjSa8vE1TFC:b-896fix) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglDisplayList.h#L19)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

no need for agl:: (please fix this in the other files as well)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-17 21:35 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/agl/2)* status: 3 of 28 files reviewed, 25 unresolved discussions (waiting on @leoetlino and @MonsterDruide1)

___
*[include/agl/aglDisplayList.h, line 33 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr95kul7ctE-G7upLTH:-Mr9JSVYDHL6qOtrtjfi:b-896fix) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglDisplayList.h#L33)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

These should be private (please fix this in the other headers as well)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-17 21:42 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/agl/2)* status: 3 of 28 files reviewed, 25 unresolved discussions (waiting on @leoetlino and @MonsterDruide1)

___
*[include/agl/aglDisplayList.h, line 46 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr95UdiDCaRjctRxy40:-Mr9Jv6r74pyCiTgrQjV:b-896fix) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglDisplayList.h#L46)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This should most likely be `const char*`
</blockquote></details>

Done.
___
*[include/agl/aglRenderBuffer.h, line 22 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr96z0_5y52A_YWcOZW:-Mr9K-dCBKyeOC186YBt:b-896fix) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglRenderBuffer.h#L22)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Vector2f, BoundBox2f
</blockquote></details>

Done.
___
*[include/agl/aglRenderTargetColor.h, line 6 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr979ghCPUtPmKMq9QI:-Mr9K3BRBRBaE1TgQ_OM:b-896fix) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglRenderTargetColor.h#L6)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

missing `public`
</blockquote></details>

Done.
___
*[include/agl/aglTextureData.h, line 12 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr97F5H-332qVcyqSdt:-Mr9K6uI8Xub89WpU-fN:b-896fix) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglTextureData.h#L12)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

explicit
</blockquote></details>

Done.
___
*[include/agl/aglTextureData.h, line 52 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr97HqV7K6CsicTLE08:-Mr9K9zZ6E74wwIS4zl8:b-896fix) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglTextureData.h#L52)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`const char*`
</blockquote></details>

Done.
___
*[include/agl/detail/aglFileIOMgr.h, line 38 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr97VCEEv1aaXqoQRQl:-Mr9KEKj2-NuCcVq4TNo:b-896fix) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/detail/aglFileIOMgr.h#L38)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

const char*
</blockquote></details>

Done.
___
*[include/agl/shader/aglShaderCompileInfo.h, line 24 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr98BFR9IIuMX5F-Ryt:-Mr9KLFIDFUhf2W0woAk:b-896fix) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/shader/aglShaderCompileInfo.h#L24)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

const char*
</blockquote></details>

Done.
___
*[include/agl/shader/aglShaderCompileInfo.h, line 27 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr985Xt3Pt1uJh758mK:-Mr9KarC26Ynrx5Lpgzx:b-ndk7d1) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/shader/aglShaderCompileInfo.h#L27)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

is the typo intended? also this should probably return a const sead::SafeString&
</blockquote></details>

Yes, the typo is intended. Changed the return type.
___
*[include/agl/shtxt/aglSyntaxTree.h, line 21 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr98_qj3OQY5I81rzur:-Mr9Kkp20fnUKQD1UqVT:b-896fix) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/shtxt/aglSyntaxTree.h#L21)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`const sead::Any...<>*`
</blockquote></details>

Done.
___
*[include/agl/shtxt/aglSyntaxTree.h, line 22 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr98gVZ-Tdq-vpq3OvK:-Mr9KvIQ1LfmI9Rrh_MG:bi7ki27) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/shtxt/aglSyntaxTree.h#L22)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

...f64?
</blockquote></details>

It has the same type as `agl::shtxt::Clause::forceNumber`, and that's a `f64` (right now).
___
*[include/agl/shtxt/aglSyntaxTree.h, line 23 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr98cI-D0gpc6dxmnq3:-Mr9KlFN-TCCJZKCefFA:b-896fix) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/shtxt/aglSyntaxTree.h#L23)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-17 21:49 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/agl/2)* status: 3 of 28 files reviewed, 25 unresolved discussions (waiting on @leoetlino and @MonsterDruide1)

___
*[include/agl/aglRenderBuffer.h, line 41 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr9747TD0iRe2vCdnmA:-Mr9M3Xw75OMTwIuM9mw:bbbi6g9) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/aglRenderBuffer.h#L41)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

are you sure this isn't an array?
</blockquote></details>

Pretty sure it is an array, as I look at the code. Changed accordingly.
___
*[include/agl/util.h, line 4 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr97PUCCS3D8rcZBton:-Mr9MHmb1PKh_qn5Cagt:b-896fix) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/util.h#L4)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

enum class?
</blockquote></details>

Done.
___
*[include/agl/driver/aglNVNtexture.h, line 18 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr98-PQAzSSsZEw7VLb:-Mr9MLNi8DQ4YfeU4A2A:b-kk2knl) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/driver/aglNVNtexture.h#L18)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Code that's been commented out should be removed.
</blockquote></details>

I'm not sure why it is commented out, but that function does exist in the decompiler. Uncommented it.
___
*[include/agl/shtxt/aglSyntaxTree.h, line 18 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr98YoG8I9KKkgmu0nm:-Mr9MgV-BaHk4KzkEE6M:b-896fix) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/shtxt/aglSyntaxTree.h#L18)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

explicit
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-17 21:55 UTC, MonsterDruide1 reviewed
> *[Reviewable](https://reviewable.io/reviews/open-ead/agl/2)* status: 2 of 28 files reviewed, 25 unresolved discussions (waiting on @leoetlino)

___
*[include/agl/shader/aglShaderCompileInfo.h, line 33 at r1](https://reviewable.io/reviews/open-ead/agl/2#-Mr98Izg9wn_KKOL9kdu:-Mr9Nz9xC8uDTu_cIaqX:b-896fix) ([raw file](https://github.com/open-ead/agl/blob/17fdb8b20ed82ccacf43a9fb56745552ef2f7916/include/agl/shader/aglShaderCompileInfo.h#L33)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

I doubt this is a PtrArrayImpl
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-13 12:36 UTC, MonsterDruide1 reviewed
Could you have another look at this? I'm still interested in getting these things added into the main repository.

> *[Reviewable](https://reviewable.io/reviews/open-ead/agl/2#-:-N9M9iLd14b2lQ6m2Jta:barhesy)* status: 0 of 28 files reviewed, 25 unresolved discussions (waiting on @leoetlino)



<!-- Sent from Reviewable.io -->

2022-08-15 21:13 UTC, leoetlino commented
Only skimmed through this as this is a rather large PR and I don't really have time to give this a proper review today, but can you add line breaks after `namespace xxx {` and before `}  // namespace xxx`? e.g.

```cpp
namespace xxx {

// stuff
// more stuff

}  // namespace xxx
```

so that things look less cramped.

Other things to fix:

- function parameters should be named whenever possible. Now obviously I understand that not every function has been properly RE'd but sometimes it's quite obvious what a parameter is. Having named parameters makes things nicer for the person who has to implement those functions (and for autocompletion/docs)
- virtual functions that are overridden should be marked `override` (or in some cases `final`), not `virtual`. This applies to virtual destructors as well
- do not use typedefs, use C++11 type aliases (`using Foo = Bar;`)
- most of the u64 usages look quite suspicious. Those u64s should probably either be pointers (use `void*` if you have no idea what the pointer type is) or `size_t`.

2023-01-21 23:15 UTC, MonsterDruide1 commented
Adjusted most of the files according to the comments, function parameters still missing in a lot of places.

Needs https://github.com/open-ead/sead/pull/119 to be merged first, fixing two signatures of virtual functions.

2023-02-17 20:58 UTC, MonsterDruide1 commented
Which/How much more changes are required here? Should I maybe split up this PR into multiple parts, so each one can be reviewed/handled individually?

2023-02-17 22:54 UTC, ThePixelGamer reviewed
Honestly leo could merge ignoring my 2 suggestions as they're pretty minor, this PR lgtm

2023-02-17 22:54 UTC, ThePixelGamer commented on include/agl/aglGPUMemBlock.hpp
> +    void initializeGfxMemoryPool(
If you pull in gfx_Types instead of gfx_Common you can just do ``nn::gfx::MemoryPool*`` here

2023-02-17 22:54 UTC, ThePixelGamer commented on include/agl/shader/aglShaderCompileInfo.h
> +                           ShaderCompileInfo::Target, bool);
Is ``ShaderCompileInfo::`` necessary here? Also afaik we wouldn't need it to fit our styling guide

2023-02-22 00:51 UTC, ThePixelGamer commented
Can you go ahead and exclude the stub.cpp from the commits? Also is there anything else that needs to be addressed?

2023-02-22 09:33 UTC, MonsterDruide1 reviewed
Done.

> *[Reviewable](https://reviewable.io/reviews/open-ead/agl/2#-:-NOsStYZ43uAhDqF1Hy2:b-896fix)* status: 0 of 49 files reviewed, 27 unresolved discussions (waiting on @leoetlino and @ThePixelGamer)

___
*[`include/agl/shader/aglShaderCompileInfo.h` line 27 at r12](https://reviewable.io/reviews/open-ead/agl/2#-Mr7rKtEzkY6Fcj_XAVN-r12-27:-NOsT7os4EJ4sSXRsjro:b-896fix) ([raw file](https://github.com/open-ead/agl/blob/24d1c2c8b116cfe40a17d1f03cd9f2b0785ca33d/include/agl/shader/aglShaderCompileInfo.h#L27)):*
<details><summary><i>Previously, ThePixelGamer (ThePixelCoder) wrote…</i></summary><blockquote>

Is ``ShaderCompileInfo::`` necessary here? Also afaik we wouldn't need it to fit our styling guide
</blockquote></details>

Done.
___
*[`include/agl/aglGPUMemBlock.hpp` line 31 at r12](https://reviewable.io/reviews/open-ead/agl/2#-N9MKapPQuw37iIcSVgu-r12-31:-NOsT2dB3A5WpicsVLB6:b-896fix) ([raw file](https://github.com/open-ead/agl/blob/24d1c2c8b116cfe40a17d1f03cd9f2b0785ca33d/include/agl/aglGPUMemBlock.hpp#L31)):*
<details><summary><i>Previously, ThePixelGamer (ThePixelCoder) wrote…</i></summary><blockquote>

If you pull in gfx_Types instead of gfx_Common you can just do ``nn::gfx::MemoryPool*`` here 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-22 16:18 UTC, ThePixelGamer requested changes
Some minor nitpicks otherwise lgtm

2023-02-22 16:18 UTC, ThePixelGamer commented on include/agl/common/aglDrawContext.h
> +    const agl::RenderBuffer* mBoundRenderBuffer;
agl:: isn't needed here

2023-02-22 16:18 UTC, ThePixelGamer commented on include/agl/common/aglGPUMemAddr.h
> +class GPUMemAddr : GPUMemAddrBase {};
Missing ``public`` presumably?

2023-02-22 16:18 UTC, ThePixelGamer commented on include/agl/common/aglTextureEnum.h
> +};
newline here

2023-02-22 16:18 UTC, ThePixelGamer commented on include/agl/shader_text/aglShaderTextDefineLinker.h
> +    bool set(sead::Heap*, Clause const*, Clause const*);
Ordering of const here is wrong, should be ``const T*``

2023-02-22 16:18 UTC, ThePixelGamer commented on include/agl/shader_text/aglShaderTextExpressionEvaluator.h
> +    ExpressionEvaluator(sead::Heap*, sead::Heap*, sead::AnyDelegate1Const<Clause*> const*);
``const T*``

2023-02-22 16:18 UTC, ThePixelGamer commented on include/agl/shader_text/aglShaderTextLexer.h
> +    void initialize(sead::Heap*, char const*, Clause*);
``const T*``

2023-02-22 16:18 UTC, ThePixelGamer commented on include/agl/shader_text/aglShaderTextDefineLinker.h
> +    u16 _46;  // 0x101
2 bools?

2023-02-22 16:18 UTC, ThePixelGamer commented on include/agl/driver/aglNVNtexture.h
> +    u8 _0[0xC0];  // NVNtexture
why not just go ahead and replace the filler array with NVNtexture? or is this comment to show you're not sure?

2023-02-22 16:18 UTC, ThePixelGamer commented on include/agl/common/aglGPUMemBlock.h
> +#include <nn/gfx/gfx_Types.h>
go ahead and add an include for the memorypool header just in case

2023-02-22 16:18 UTC, ThePixelGamer commented on CMakeLists.txt
> -
I think these spaces in between the src directories was intentional, reason for removal?

2023-02-22 16:48 UTC, ThePixelGamer commented
``detail/aglPrivateResource.h`` still uses the old hpp include, can you push a fix?

2023-02-22 20:36 UTC, MonsterDruide1 commented on include/agl/common/aglDrawContext.h
> +    const agl::RenderBuffer* mBoundRenderBuffer;
There are some more `agl::` references scattered throughout the repo, might get a followup-PR to remove all of them if I remember to do that.

2023-02-22 20:43 UTC, MonsterDruide1 commented on CMakeLists.txt
> -
No real reason, I just re-generated the whole `CMakeLists.txt` using `find` and didn't put those spaces back into place.

2023-02-22 20:48 UTC, MonsterDruide1 commented on include/agl/common/aglGPUMemBlock.h
> +#include <nn/gfx/gfx_Types.h>
Which one, and why?
`MemoryAttribute` comes from `aglGPUCommon`, and all other `MemoryPool[Heap]` stuff is forward-declared in here.

2023-02-22 20:54 UTC, MonsterDruide1 commented on include/agl/driver/aglNVNtexture.h
> +    u8 _0[0xC0];  // NVNtexture
I can only stress again - most of the stuff in here is not properly researched by me, I'm just trying to get the information together from different sources. This one specifically seems to be a `NVNtexture` though.

2023-02-22 21:01 UTC, MonsterDruide1 commented on include/agl/shader_text/aglShaderTextDefineLinker.h
> +    u16 _46;  // 0x101
Probably... I don't see them being used anywhere except being set in the constructor, so can't verify it.

2023-02-22 21:27 UTC, ThePixelGamer commented on include/agl/common/aglGPUMemBlock.h
> +#include <nn/gfx/gfx_Types.h>
The nn::gfx one but I realize it's not needed due to it just using it for a pointer

2023-02-23 07:13 UTC, ThePixelGamer approved these changes

2023-02-23 07:13 UTC, ThePixelGamer commented
LGTM I'll :shipit: whenever you give the go ahead @MonsterDruide1

2023-02-24 20:00 UTC, MonsterDruide1 commented
Alright, then - go!

2023-02-24 22:38 UTC, merged